# Generated by Django 4.0.5 on 2022-09-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
